services:
  - type: web
    name: fx-vm-bot
    runtime: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: BOT_USERNAME
        sync: false
      - key: ADMIN_CONTACT
        sync: false
      - key: WEBAPP_URL
        sync: false
      - key: PG_SSL
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: fx-vm-db
          property: connectionString

databases:
  - name: fx-vm-db
    plan: starter
